name: Deploy-Static-V1

on:
  workflow_dispatch:  # Allows manual deployment with branch selection
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch || 'main' }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --configuration=production

    - name: Build and Deploy Angular App
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token
        action: "upload"
        app_location: "/" # Path to Angular project root
        api_location: "" # Leave empty if there's no API
        output_location: "dist/taskapp-web/browser" # Updated to point to 'browser'
