name: Deploy-V2

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the Node.js version your app requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Step 5: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: taskapp  # Replace with your Azure App Service name
          slot-name: production  # Optional: Specify a deployment slot
          package: dist/taskapp-web  # Path to the built Angular app