name: Deploy-V1

on:
  workflow_dispatch:  # Allows manual deployment with branch selection
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod

      - name: Verify Build Output
        run: ls -la dist/taskapp-web

      - name: Zip Build Files
        run: cd dist/taskapp-web && zip -r ../taskapp-web.zip . && cd ../../

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Angular App to Azure
        run: |
          az webapp deployment source config-zip --resource-group taskapp-rg --name taskapp --src dist/taskapp-web.zip
